-- ============================================================================
-- Migration 004: Seed completo de keywords do Palavras_Chave.md
-- ============================================================================

-- Limpa seeds anteriores para evitar duplicatas
-- (ON CONFLICT DO NOTHING cuida disso, mas fica explícito)

INSERT INTO spy_keywords (keyword, category, language) VALUES
  -- ═══ GERAL (PT) ═══
  ('truque', 'geral', 'pt'),
  ('método', 'geral', 'pt'),
  ('caseiro', 'geral', 'pt'),
  ('truquezinho', 'geral', 'pt'),
  ('sujo', 'geral', 'pt'),
  ('secreto', 'geral', 'pt'),
  ('segredo', 'geral', 'pt'),
  ('matinal', 'geral', 'pt'),
  ('verdadeira causa', 'geral', 'pt'),
  ('causa raiz', 'geral', 'pt'),
  ('receita', 'geral', 'pt'),
  ('truque caseiro', 'geral', 'pt'),
  ('truque simples', 'geral', 'pt'),
  ('truque natural', 'geral', 'pt'),
  ('truque secreto', 'geral', 'pt'),
  ('método natural', 'geral', 'pt'),
  ('método caseiro', 'geral', 'pt'),
  ('método simples', 'geral', 'pt'),
  ('m��todo desconhecido', 'geral', 'pt'),
  ('método revolucionário', 'geral', 'pt'),
  ('ritual matinal', 'geral', 'pt'),
  ('ritual noturno', 'geral', 'pt'),
  ('ritual de 10 segundos', 'geral', 'pt'),
  ('ritual de 15 segundos', 'geral', 'pt'),
  ('hábito simples', 'geral', 'pt'),
  ('hábito escondido', 'geral', 'pt'),
  ('protocolo', 'geral', 'pt'),
  ('protocolo natural', 'geral', 'pt'),
  ('protocolo caseiro', 'geral', 'pt'),
  ('protocolo matinal', 'geral', 'pt'),
  ('método secreto', 'geral', 'pt'),
  ('segredo caseiro', 'geral', 'pt'),
  ('segredo natural', 'geral', 'pt'),
  ('técnica secreta', 'geral', 'pt'),
  ('milagre escondido', 'geral', 'pt'),
  ('o que ninguém fala', 'geral', 'pt'),
  ('o que ninguém conta', 'geral', 'pt'),
  ('o que médicos não contam', 'geral', 'pt'),
  ('escondido da população', 'geral', 'pt'),
  ('proibido pela indústria', 'geral', 'pt'),
  ('removido pela anvisa', 'geral', 'pt'),
  ('vídeo proibido', 'geral', 'pt'),
  ('vídeo derrubado', 'geral', 'pt'),
  ('antes que tirem do ar', 'geral', 'pt'),
  ('antes que removam', 'geral', 'pt'),
  ('caseirinho', 'geral', 'pt'),
  ('solução caseira', 'geral', 'pt'),
  ('receita caseira', 'geral', 'pt'),
  ('receita simples', 'geral', 'pt'),
  ('receita natural', 'geral', 'pt'),
  ('receita antiga', 'geral', 'pt'),
  ('fácil de fazer', 'geral', 'pt'),
  ('do dia a dia', 'geral', 'pt'),
  ('ingrediente que você tem em casa', 'geral', 'pt'),
  ('misturinha', 'geral', 'pt'),
  ('mistura poderosa', 'geral', 'pt'),
  ('causa principal', 'geral', 'pt'),
  ('problema oculto', 'geral', 'pt'),
  ('o que está por trás', 'geral', 'pt'),
  ('a raiz do problema', 'geral', 'pt'),
  ('motivo real', 'geral', 'pt'),
  ('por que nada funciona', 'geral', 'pt'),
  ('o que bloqueia seu corpo', 'geral', 'pt'),
  ('razão escondida', 'geral', 'pt'),
  ('gatilho oculto', 'geral', 'pt'),
  ('trava hormonal', 'geral', 'pt'),
  ('comprovado', 'geral', 'pt'),
  ('estudos mostram', 'geral', 'pt'),
  ('estudo recente', 'geral', 'pt'),
  ('pesquisadores', 'geral', 'pt'),
  ('cientistas', 'geral', 'pt'),
  ('pesquisadores de harvard', 'geral', 'pt'),
  ('especialistas', 'geral', 'pt'),
  ('médicos revelam', 'geral', 'pt'),
  ('testado e aprovado', 'geral', 'pt'),
  ('baseado em pesquisas', 'geral', 'pt'),
  ('chocante', 'geral', 'pt'),
  ('surpreendente', 'geral', 'pt'),
  ('bizarro', 'geral', 'pt'),
  ('estranho', 'geral', 'pt'),
  ('insólito', 'geral', 'pt'),
  ('escondido', 'geral', 'pt'),
  ('oculto', 'geral', 'pt'),
  ('esquecido', 'geral', 'pt'),
  ('mistério', 'geral', 'pt'),
  ('descoberta', 'geral', 'pt'),
  ('revelado', 'geral', 'pt'),
  ('finalmente revelado', 'geral', 'pt'),
  ('descoberta acidental', 'geral', 'pt'),
  -- ═══ GERAL (EN) ═══
  ('watch the video', 'geral', 'en'),
  ('click below', 'geral', 'en'),
  ('learn more', 'geral', 'en'),
  ('free video', 'geral', 'en'),
  ('watch before removed', 'geral', 'en'),
  ('secret method', 'geral', 'en'),
  ('secret trick', 'geral', 'en'),
  ('simple trick', 'geral', 'en'),
  ('natural trick', 'geral', 'en'),
  ('hidden trick', 'geral', 'en'),
  ('homemade trick', 'geral', 'en'),
  ('weird trick', 'geral', 'en'),
  ('bizarre trick', 'geral', 'en'),
  ('strange trick', 'geral', 'en'),
  ('odd trick', 'geral', 'en'),
  ('10-second ritual', 'geral', 'en'),
  ('15-second ritual', 'geral', 'en'),
  ('ancient formula', 'geral', 'en'),
  ('forbidden method', 'geral', 'en'),
  ('lost method', 'geral', 'en'),
  ('simple recipe', 'geral', 'en'),
  ('easy recipe', 'geral', 'en'),
  ('home remedy', 'geral', 'en'),
  ('home solution', 'geral', 'en'),
  ('natural remedy', 'geral', 'en'),
  ('natural method', 'geral', 'en'),
  ('natural solution', 'geral', 'en'),
  ('herbal blend', 'geral', 'en'),
  ('ancient herb', 'geral', 'en'),
  ('before it''s removed', 'geral', 'en'),
  ('they don''t want you to know', 'geral', 'en'),
  ('hidden from the public', 'geral', 'en'),
  ('secretly suppressed', 'geral', 'en'),
  ('industry hates', 'geral', 'en'),
  ('big pharma hates', 'geral', 'en'),
  ('blue pill industry hates', 'geral', 'en'),
  ('mind-blowing', 'geral', 'en'),
  ('eye-opening', 'geral', 'en'),
  ('little-known', 'geral', 'en'),
  ('viral video', 'geral', 'en'),
  ('million views', 'geral', 'en'),
  ('pharmaceutical industry hates it', 'geral', 'en'),
  ('kept hidden', 'geral', 'en'),
  ('industry doesn''t want you to know', 'geral', 'en'),
  ('people are talking about it', 'geral', 'en'),
  ('last chance', 'geral', 'en'),
  ('only available for a few hours', 'geral', 'en'),
  ('watch before it goes offline', 'geral', 'en'),
  ('video removed', 'geral', 'en'),
  ('limited time', 'geral', 'en'),
  ('don''t miss it', 'geral', 'en'),
  ('act now', 'geral', 'en'),
  ('click learn more', 'geral', 'en'),
  ('people noticing', 'geral', 'en'),
  ('reversal ritual', 'geral', 'en'),
  ('homemade solution', 'geral', 'en'),
  -- ═══ EMAGRECIMENTO (PT) ═══
  ('receitinha', 'emagrecimento', 'pt'),
  ('especialista revela', 'emagrecimento', 'pt'),
  ('bebida caseira', 'emagrecimento', 'pt'),
  ('metabolismo', 'emagrecimento', 'pt'),
  ('acelerar o metabolismo', 'emagrecimento', 'pt'),
  ('derreter', 'emagrecimento', 'pt'),
  ('secar', 'emagrecimento', 'pt'),
  ('gordura localizada', 'emagrecimento', 'pt'),
  ('gordurinha', 'emagrecimento', 'pt'),
  ('truque matinal', 'emagrecimento', 'pt'),
  ('queimar gordura', 'emagrecimento', 'pt'),
  ('segredinho', 'emagrecimento', 'pt'),
  ('semente bariátrica', 'emagrecimento', 'pt'),
  ('monjaro', 'emagrecimento', 'pt'),
  -- ═══ EMAGRECIMENTO (EN) ═══
  ('i dropped from', 'emagrecimento', 'en'),
  ('lose weight fast', 'emagrecimento', 'en'),
  ('burn fat', 'emagrecimento', 'en'),
  ('melt fat', 'emagrecimento', 'en'),
  ('lose pounds', 'emagrecimento', 'en'),
  ('lose weight quickly', 'emagrecimento', 'en'),
  ('fat-burning', 'emagrecimento', 'en'),
  ('drop pounds', 'emagrecimento', 'en'),
  ('stubborn fat', 'emagrecimento', 'en'),
  ('belly fat', 'emagrecimento', 'en'),
  ('slim down', 'emagrecimento', 'en'),
  ('clothes getting loose', 'emagrecimento', 'en'),
  ('glp-1', 'emagrecimento', 'en'),
  ('ozempic', 'emagrecimento', 'en'),
  ('mounjaro effect', 'emagrecimento', 'en'),
  ('weight loss injections', 'emagrecimento', 'en'),
  ('at-home bariatric', 'emagrecimento', 'en'),
  ('mimics injections', 'emagrecimento', 'en'),
  ('feeling good in the mirror', 'emagrecimento', 'en'),
  ('metabolism speeding up', 'emagrecimento', 'en'),
  ('waking up lighter', 'emagrecimento', 'en'),
  ('tried everything', 'emagrecimento', 'en'),
  ('yo-yo effect', 'emagrecimento', 'en'),
  ('struggled with weight', 'emagrecimento', 'en'),
  ('nothing worked before', 'emagrecimento', 'en'),
  ('gym didn''t work', 'emagrecimento', 'en'),
  -- ═══ ED (PT) ═══
  ('viagra', 'ed', 'pt'),
  ('azulzinho', 'ed', 'pt'),
  -- ═══ ED (EN) ═══
  ('blue pills', 'ed', 'en'),
  ('couldn''t perform', 'ed', 'en'),
  ('disappointed in bed', 'ed', 'en'),
  ('performance problems', 'ed', 'en'),
  ('couldn''t stay hard', 'ed', 'en'),
  ('weak erections', 'ed', 'en'),
  ('hard as a rock', 'ed', 'en'),
  ('last longer', 'ed', 'en'),
  ('7x more potent', 'ed', 'en'),
  ('increased blood flow', 'ed', 'en'),
  ('wake up with morning wood', 'ed', 'en'),
  ('blue pill industry', 'ed', 'en'),
  ('they don''t want you to see it', 'ed', 'en'),
  ('like the injections but natural', 'ed', 'en'),
  ('banned video', 'ed', 'en'),
  -- ═══ DIABETES (PT) ═══
  ('açúcar no sangue', 'diabetes', 'pt'),
  ('glicose', 'diabetes', 'pt'),
  ('canetinha', 'diabetes', 'pt'),
  ('diabetes', 'diabetes', 'pt'),
  ('insulina', 'diabetes', 'pt'),
  -- ═══ DIABETES (EN) ═══
  ('type 2 diabetes', 'diabetes', 'en'),
  ('blood sugar', 'diabetes', 'en'),
  ('metformin', 'diabetes', 'en'),
  ('reverse type 2', 'diabetes', 'en'),
  ('lower blood sugar', 'diabetes', 'en'),
  ('high blood sugar', 'diabetes', 'en'),
  ('blood sugar levels', 'diabetes', 'en'),
  ('a1c', 'diabetes', 'en'),
  ('insulin resistance', 'diabetes', 'en'),
  ('finger pricking', 'diabetes', 'en'),
  ('they want to keep you sick', 'diabetes', 'en'),
  ('hidden cause', 'diabetes', 'en'),
  ('toxic enemy', 'diabetes', 'en'),
  ('native trick', 'diabetes', 'en'),
  ('native herbs', 'diabetes', 'en'),
  ('herbal ritual', 'diabetes', 'en'),
  ('japanese trick', 'diabetes', 'en'),
  ('15 second trick', 'diabetes', 'en'),
  ('30 second recipe', 'diabetes', 'en'),
  ('no medications', 'diabetes', 'en'),
  ('glucose under 100', 'diabetes', 'en'),
  ('a1c down to 5%', 'diabetes', 'en'),
  ('regain control', 'diabetes', 'en'),
  ('works in days', 'diabetes', 'en'),
  ('big pharma', 'diabetes', 'en'),
  ('hidden truth', 'diabetes', 'en'),
  ('before they remove it', 'diabetes', 'en'),
  ('free presentation', 'diabetes', 'en'),
  ('discover the truth', 'diabetes', 'en'),
  ('act fast', 'diabetes', 'en')
ON CONFLICT DO NOTHING;
