-- Migration 007 — Rebuild completo de spy_keywords a partir do Palavras_Chave (1).md
-- Estratégia:
--   1. Cria nicho "low_ticket" (geral / persuasão).
--   2. Limpa TODAS as keywords antigas (DELETE).
--   3. Reinsere por nicho (emagrecimento / saude-masculina / diabetes / low_ticket).
--   ON CONFLICT DO NOTHING — uniqueness é case-insensitive (idx_spy_keywords_unique em LOWER(keyword)).
--   Ordem: nichos específicos PRIMEIRO, low_ticket por último, para que keywords compartilhadas
--   (ex: "ritual matinal", "viral video") fiquem no nicho mais específico.

-- ══════════════════════════════════════════
-- 1. Novo nicho: Low Ticket
-- ══════════════════════════════════════════
INSERT INTO niches (id, name, emoji, color, is_active) VALUES
  ('low_ticket', 'low ticket', '🎫', '#F4C430', true)
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════════
-- 2. Wipe completo
-- ══════════════════════════════════════════
DELETE FROM spy_keywords;

-- ══════════════════════════════════════════
-- 3. EMAGRECIMENTO (PT + EN)
-- ══════════════════════════════════════════
INSERT INTO spy_keywords (keyword, category, language, niche_id) VALUES
  -- PT
  ('gordura',                     'emagrecimento', 'pt', 'emagrecimento'),
  ('peso',                        'emagrecimento', 'pt', 'emagrecimento'),
  ('receitinha',                  'emagrecimento', 'pt', 'emagrecimento'),
  ('especialista revela',         'emagrecimento', 'pt', 'emagrecimento'),
  ('truque caseiro',              'emagrecimento', 'pt', 'emagrecimento'),
  ('receita simples',             'emagrecimento', 'pt', 'emagrecimento'),
  ('ritual matinal',              'emagrecimento', 'pt', 'emagrecimento'),
  ('ritual noturno',              'emagrecimento', 'pt', 'emagrecimento'),
  ('bebida caseira',              'emagrecimento', 'pt', 'emagrecimento'),
  ('metabolismo',                 'emagrecimento', 'pt', 'emagrecimento'),
  ('acelerar o metabolismo',      'emagrecimento', 'pt', 'emagrecimento'),
  ('derreter',                    'emagrecimento', 'pt', 'emagrecimento'),
  ('secar',                       'emagrecimento', 'pt', 'emagrecimento'),
  ('gordura localizada',          'emagrecimento', 'pt', 'emagrecimento'),
  ('banha',                       'emagrecimento', 'pt', 'emagrecimento'),
  ('gordurinha',                  'emagrecimento', 'pt', 'emagrecimento'),
  ('truque matinal',              'emagrecimento', 'pt', 'emagrecimento'),
  ('queimar gordura',             'emagrecimento', 'pt', 'emagrecimento'),
  ('segredinho',                  'emagrecimento', 'pt', 'emagrecimento'),
  ('misturinha',                  'emagrecimento', 'pt', 'emagrecimento'),
  ('dieta',                       'emagrecimento', 'pt', 'emagrecimento'),
  ('semente bariátrica',          'emagrecimento', 'pt', 'emagrecimento'),
  ('monjaro',                     'emagrecimento', 'pt', 'emagrecimento'),
  -- EN
  ('pounds',                      'emagrecimento', 'en', 'emagrecimento'),
  ('i dropped from',              'emagrecimento', 'en', 'emagrecimento'),
  ('bariatric',                   'emagrecimento', 'en', 'emagrecimento'),
  ('lose weight fast',            'emagrecimento', 'en', 'emagrecimento'),
  ('burn fat',                    'emagrecimento', 'en', 'emagrecimento'),
  ('melt fat',                    'emagrecimento', 'en', 'emagrecimento'),
  ('lose pounds',                 'emagrecimento', 'en', 'emagrecimento'),
  ('lose weight quickly',         'emagrecimento', 'en', 'emagrecimento'),
  ('fat-burning',                 'emagrecimento', 'en', 'emagrecimento'),
  ('drop pounds',                 'emagrecimento', 'en', 'emagrecimento'),
  ('stubborn fat',                'emagrecimento', 'en', 'emagrecimento'),
  ('belly fat',                   'emagrecimento', 'en', 'emagrecimento'),
  ('slim down',                   'emagrecimento', 'en', 'emagrecimento'),
  ('waist',                       'emagrecimento', 'en', 'emagrecimento'),
  ('arms',                        'emagrecimento', 'en', 'emagrecimento'),
  ('thighs',                      'emagrecimento', 'en', 'emagrecimento'),
  ('hips',                        'emagrecimento', 'en', 'emagrecimento'),
  ('clothes getting loose',       'emagrecimento', 'en', 'emagrecimento'),
  ('glp-1',                       'emagrecimento', 'en', 'emagrecimento'),
  ('gip',                         'emagrecimento', 'en', 'emagrecimento'),
  ('ozempic',                     'emagrecimento', 'en', 'emagrecimento'),
  ('mounjaro effect',             'emagrecimento', 'en', 'emagrecimento'),
  ('weight loss injections',      'emagrecimento', 'en', 'emagrecimento'),
  ('injection pens',              'emagrecimento', 'en', 'emagrecimento'),
  ('at-home bariatric',           'emagrecimento', 'en', 'emagrecimento'),
  ('mimics injections',           'emagrecimento', 'en', 'emagrecimento'),
  ('viral video',                 'emagrecimento', 'en', 'emagrecimento'),
  ('million views',               'emagrecimento', 'en', 'emagrecimento'),
  ('celebrities',                 'emagrecimento', 'en', 'emagrecimento'),
  ('hollywood celebrities',       'emagrecimento', 'en', 'emagrecimento'),
  ('feeling good in the mirror', 'emagrecimento', 'en', 'emagrecimento'),
  ('husband complimenting',       'emagrecimento', 'en', 'emagrecimento'),
  ('wearing a bikini',            'emagrecimento', 'en', 'emagrecimento'),
  ('energy came back',            'emagrecimento', 'en', 'emagrecimento'),
  ('look younger',                'emagrecimento', 'en', 'emagrecimento'),
  ('metabolism speeding up',      'emagrecimento', 'en', 'emagrecimento'),
  ('waking up lighter',           'emagrecimento', 'en', 'emagrecimento'),
  ('tried everything',            'emagrecimento', 'en', 'emagrecimento'),
  ('yo-yo effect',                'emagrecimento', 'en', 'emagrecimento'),
  ('struggled with weight',       'emagrecimento', 'en', 'emagrecimento'),
  ('nothing worked before',       'emagrecimento', 'en', 'emagrecimento'),
  ('felt hopeless',               'emagrecimento', 'en', 'emagrecimento'),
  ('restrictive diets',           'emagrecimento', 'en', 'emagrecimento'),
  ('fasting',                     'emagrecimento', 'en', 'emagrecimento'),
  ('calorie counting',            'emagrecimento', 'en', 'emagrecimento'),
  ('gym didn''t work',            'emagrecimento', 'en', 'emagrecimento')
ON CONFLICT DO NOTHING;

-- ══════════════════════════════════════════
-- 4. SAÚDE MASCULINA / ED (PT + EN)
-- ══════════════════════════════════════════
INSERT INTO spy_keywords (keyword, category, language, niche_id) VALUES
  -- PT
  ('viagra',                          'ed', 'pt', 'saude-masculina'),
  ('azulzinho',                       'ed', 'pt', 'saude-masculina'),
  -- EN
  ('blue pills',                      'ed', 'en', 'saude-masculina'),
  ('couldn''t perform',               'ed', 'en', 'saude-masculina'),
  ('disappointed in bed',             'ed', 'en', 'saude-masculina'),
  ('pumps',                           'ed', 'en', 'saude-masculina'),
  ('extenders',                       'ed', 'en', 'saude-masculina'),
  ('expensive treatments',            'ed', 'en', 'saude-masculina'),
  ('embarrassment',                   'ed', 'en', 'saude-masculina'),
  ('performance problems',            'ed', 'en', 'saude-masculina'),
  ('short-lasting',                   'ed', 'en', 'saude-masculina'),
  ('not lasting long',                'ed', 'en', 'saude-masculina'),
  ('couldn''t stay hard',             'ed', 'en', 'saude-masculina'),
  ('weak erections',                  'ed', 'en', 'saude-masculina'),
  ('couldn''t satisfy woman',         'ed', 'en', 'saude-masculina'),
  ('hard as a rock',                  'ed', 'en', 'saude-masculina'),
  ('last longer',                     'ed', 'en', 'saude-masculina'),
  ('7x more potent',                  'ed', 'en', 'saude-masculina'),
  ('2 hours straight',                'ed', 'en', 'saude-masculina'),
  ('3 hours straight',                'ed', 'en', 'saude-masculina'),
  ('20-year-old performance',         'ed', 'en', 'saude-masculina'),
  ('increased blood flow',            'ed', 'en', 'saude-masculina'),
  ('wake up with morning wood',       'ed', 'en', 'saude-masculina'),
  ('always ready',                    'ed', 'en', 'saude-masculina'),
  ('increases size',                  'ed', 'en', 'saude-masculina'),
  ('makes you harder',                'ed', 'en', 'saude-masculina'),
  ('harder thicker stronger',         'ed', 'en', 'saude-masculina'),
  ('women can''t walk after',         'ed', 'en', 'saude-masculina'),
  ('woman soaking wet',               'ed', 'en', 'saude-masculina'),
  ('multiple orgasms',                'ed', 'en', 'saude-masculina'),
  ('woman begging for more',          'ed', 'en', 'saude-masculina'),
  ('adult film actors',               'ed', 'en', 'saude-masculina'),
  ('porn actor',                      'ed', 'en', 'saude-masculina'),
  ('rocco siffredi',                  'ed', 'en', 'saude-masculina'),
  ('kevin costner',                   'ed', 'en', 'saude-masculina'),
  ('comments saying it works',        'ed', 'en', 'saude-masculina'),
  ('banned video',                    'ed', 'en', 'saude-masculina'),
  ('blue pill industry',              'ed', 'en', 'saude-masculina'),
  ('they hate it',                    'ed', 'en', 'saude-masculina'),
  ('they don''t want you to see it',  'ed', 'en', 'saude-masculina'),
  ('like the injections but natural', 'ed', 'en', 'saude-masculina')
ON CONFLICT DO NOTHING;

-- ══════════════════════════════════════════
-- 5. DIABETES (PT + EN)
-- ══════════════════════════════════════════
INSERT INTO spy_keywords (keyword, category, language, niche_id) VALUES
  -- PT
  ('açúcar no sangue',                          'diabetes', 'pt', 'diabetes'),
  ('glicose',                                   'diabetes', 'pt', 'diabetes'),
  ('canetinha',                                 'diabetes', 'pt', 'diabetes'),
  ('diabetes',                                  'diabetes', 'pt', 'diabetes'),
  ('insulina',                                  'diabetes', 'pt', 'diabetes'),
  ('glicemia',                                  'diabetes', 'pt', 'diabetes'),
  -- EN
  ('type 2',                                    'diabetes', 'en', 'diabetes'),
  ('blood sugar',                               'diabetes', 'en', 'diabetes'),
  ('metformin',                                 'diabetes', 'en', 'diabetes'),
  ('reverse type 2',                            'diabetes', 'en', 'diabetes'),
  ('lower blood sugar',                         'diabetes', 'en', 'diabetes'),
  ('high blood sugar',                          'diabetes', 'en', 'diabetes'),
  ('blood sugar levels',                        'diabetes', 'en', 'diabetes'),
  ('a1c',                                       'diabetes', 'en', 'diabetes'),
  ('type 2 diabetes',                           'diabetes', 'en', 'diabetes'),
  ('insulin resistance',                        'diabetes', 'en', 'diabetes'),
  ('glucose',                                   'diabetes', 'en', 'diabetes'),
  ('spikes',                                    'diabetes', 'en', 'diabetes'),
  ('beta cells',                                'diabetes', 'en', 'diabetes'),
  ('pancreas',                                  'diabetes', 'en', 'diabetes'),
  ('fatigue',                                   'diabetes', 'en', 'diabetes'),
  ('excessive hunger',                          'diabetes', 'en', 'diabetes'),
  ('frequent bathroom trips',                   'diabetes', 'en', 'diabetes'),
  ('tingling in hands and feet',                'diabetes', 'en', 'diabetes'),
  ('cravings',                                  'diabetes', 'en', 'diabetes'),
  ('dangerous levels',                          'diabetes', 'en', 'diabetes'),
  ('finger pricking',                           'diabetes', 'en', 'diabetes'),
  ('medications',                               'diabetes', 'en', 'diabetes'),
  ('insulin',                                   'diabetes', 'en', 'diabetes'),
  ('pharmaceutical industry',                   'diabetes', 'en', 'diabetes'),
  ('they want to keep you sick',                'diabetes', 'en', 'diabetes'),
  ('doing everything right but nothing changes','diabetes', 'en', 'diabetes'),
  ('parasite',                                  'diabetes', 'en', 'diabetes'),
  ('bacteria',                                  'diabetes', 'en', 'diabetes'),
  ('disgusting creature',                       'diabetes', 'en', 'diabetes'),
  ('1 inch parasite',                           'diabetes', 'en', 'diabetes'),
  ('real culprit',                              'diabetes', 'en', 'diabetes'),
  ('not sugar or carbs',                        'diabetes', 'en', 'diabetes'),
  ('hidden cause',                              'diabetes', 'en', 'diabetes'),
  ('toxic enemy',                               'diabetes', 'en', 'diabetes'),
  ('something feeding on your insulin',         'diabetes', 'en', 'diabetes'),
  ('destroys beta cells',                       'diabetes', 'en', 'diabetes'),
  ('attached to pancreas',                      'diabetes', 'en', 'diabetes'),
  ('native trick',                              'diabetes', 'en', 'diabetes'),
  ('native herbs',                              'diabetes', 'en', 'diabetes'),
  ('herbal ritual',                             'diabetes', 'en', 'diabetes'),
  ('japanese trick',                            'diabetes', 'en', 'diabetes'),
  ('japanese solution',                         'diabetes', 'en', 'diabetes'),
  ('15 second trick',                           'diabetes', 'en', 'diabetes'),
  ('30 second recipe',                          'diabetes', 'en', 'diabetes'),
  ('five minute tutorial',                      'diabetes', 'en', 'diabetes'),
  ('presentation',                              'diabetes', 'en', 'diabetes'),
  ('no medications',                            'diabetes', 'en', 'diabetes'),
  ('no pills',                                  'diabetes', 'en', 'diabetes'),
  ('no chemicals',                              'diabetes', 'en', 'diabetes'),
  ('reversable condition',                      'diabetes', 'en', 'diabetes'),
  ('glucose under 100',                         'diabetes', 'en', 'diabetes'),
  ('a1c down to 5%',                            'diabetes', 'en', 'diabetes'),
  ('regain control',                            'diabetes', 'en', 'diabetes'),
  ('regain freedom',                            'diabetes', 'en', 'diabetes'),
  ('works in hours',                            'diabetes', 'en', 'diabetes'),
  ('works in days',                             'diabetes', 'en', 'diabetes'),
  ('experts',                                   'diabetes', 'en', 'diabetes'),
  ('dr. oz',                                    'diabetes', 'en', 'diabetes'),
  ('abc',                                       'diabetes', 'en', 'diabetes'),
  ('cnn',                                       'diabetes', 'en', 'diabetes'),
  ('japanese university',                       'diabetes', 'en', 'diabetes'),
  ('cambridge university',                      'diabetes', 'en', 'diabetes'),
  ('big pharma',                                'diabetes', 'en', 'diabetes'),
  ('they want to take the video down',          'diabetes', 'en', 'diabetes'),
  ('hidden truth',                              'diabetes', 'en', 'diabetes'),
  ('won''t stay online',                        'diabetes', 'en', 'diabetes'),
  ('last time i''m sharing this',               'diabetes', 'en', 'diabetes'),
  ('before they remove it',                     'diabetes', 'en', 'diabetes'),
  ('watch while it''s still available',         'diabetes', 'en', 'diabetes'),
  ('click the link',                            'diabetes', 'en', 'diabetes'),
  ('free presentation',                         'diabetes', 'en', 'diabetes'),
  ('learn how',                                 'diabetes', 'en', 'diabetes'),
  ('discover the truth',                        'diabetes', 'en', 'diabetes'),
  ('see the tutorial',                          'diabetes', 'en', 'diabetes'),
  ('act fast',                                  'diabetes', 'en', 'diabetes')
ON CONFLICT DO NOTHING;

-- ══════════════════════════════════════════
-- 6. LOW TICKET (PT + EN) — geral / persuasão
-- ══════════════════════════════════════════
INSERT INTO spy_keywords (keyword, category, language, niche_id) VALUES
  -- PT
  ('truque',                          'low_ticket', 'pt', 'low_ticket'),
  ('método',                          'low_ticket', 'pt', 'low_ticket'),
  ('caseiro',                         'low_ticket', 'pt', 'low_ticket'),
  ('truquezinho',                     'low_ticket', 'pt', 'low_ticket'),
  ('natural',                         'low_ticket', 'pt', 'low_ticket'),
  ('sujo',                            'low_ticket', 'pt', 'low_ticket'),
  ('secreto',                         'low_ticket', 'pt', 'low_ticket'),
  ('segredo',                         'low_ticket', 'pt', 'low_ticket'),
  ('ritual',                          'low_ticket', 'pt', 'low_ticket'),
  ('matinal',                         'low_ticket', 'pt', 'low_ticket'),
  ('verdadeira causa',                'low_ticket', 'pt', 'low_ticket'),
  ('causa raiz',                      'low_ticket', 'pt', 'low_ticket'),
  ('simples',                         'low_ticket', 'pt', 'low_ticket'),
  ('receita',                         'low_ticket', 'pt', 'low_ticket'),
  ('truque simples',                  'low_ticket', 'pt', 'low_ticket'),
  ('truque natural',                  'low_ticket', 'pt', 'low_ticket'),
  ('truque secreto',                  'low_ticket', 'pt', 'low_ticket'),
  ('método natural',                  'low_ticket', 'pt', 'low_ticket'),
  ('método caseiro',                  'low_ticket', 'pt', 'low_ticket'),
  ('método simples',                  'low_ticket', 'pt', 'low_ticket'),
  ('método desconhecido',             'low_ticket', 'pt', 'low_ticket'),
  ('método revolucionário',           'low_ticket', 'pt', 'low_ticket'),
  ('ritual de 10 segundos',           'low_ticket', 'pt', 'low_ticket'),
  ('ritual de 15 segundos',           'low_ticket', 'pt', 'low_ticket'),
  ('hábito simples',                  'low_ticket', 'pt', 'low_ticket'),
  ('hábito escondido',                'low_ticket', 'pt', 'low_ticket'),
  ('protocolo',                       'low_ticket', 'pt', 'low_ticket'),
  ('protocolo natural',               'low_ticket', 'pt', 'low_ticket'),
  ('protocolo caseiro',               'low_ticket', 'pt', 'low_ticket'),
  ('protocolo matinal',               'low_ticket', 'pt', 'low_ticket'),
  ('método secreto',                  'low_ticket', 'pt', 'low_ticket'),
  ('segredo caseiro',                 'low_ticket', 'pt', 'low_ticket'),
  ('segredo natural',                 'low_ticket', 'pt', 'low_ticket'),
  ('técnica secreta',                 'low_ticket', 'pt', 'low_ticket'),
  ('milagre escondido',               'low_ticket', 'pt', 'low_ticket'),
  ('o que ninguém fala',              'low_ticket', 'pt', 'low_ticket'),
  ('o que ninguém conta',             'low_ticket', 'pt', 'low_ticket'),
  ('o que médicos não contam',        'low_ticket', 'pt', 'low_ticket'),
  ('escondido da população',          'low_ticket', 'pt', 'low_ticket'),
  ('proibido pela indústria',         'low_ticket', 'pt', 'low_ticket'),
  ('removido pela anvisa',            'low_ticket', 'pt', 'low_ticket'),
  ('vídeo proibido',                  'low_ticket', 'pt', 'low_ticket'),
  ('vídeo derrubado',                 'low_ticket', 'pt', 'low_ticket'),
  ('antes que tirem do ar',           'low_ticket', 'pt', 'low_ticket'),
  ('antes que removam',               'low_ticket', 'pt', 'low_ticket'),
  ('caseirinho',                      'low_ticket', 'pt', 'low_ticket'),
  ('solução caseira',                 'low_ticket', 'pt', 'low_ticket'),
  ('receita caseira',                 'low_ticket', 'pt', 'low_ticket'),
  ('receita natural',                 'low_ticket', 'pt', 'low_ticket'),
  ('receita antiga',                  'low_ticket', 'pt', 'low_ticket'),
  ('fácil de fazer',                  'low_ticket', 'pt', 'low_ticket'),
  ('fácil',                           'low_ticket', 'pt', 'low_ticket'),
  ('do dia a dia',                    'low_ticket', 'pt', 'low_ticket'),
  ('ingrediente que você tem em casa','low_ticket', 'pt', 'low_ticket'),
  ('mistura poderosa',                'low_ticket', 'pt', 'low_ticket'),
  ('causa principal',                 'low_ticket', 'pt', 'low_ticket'),
  ('problema oculto',                 'low_ticket', 'pt', 'low_ticket'),
  ('o que está por trás',             'low_ticket', 'pt', 'low_ticket'),
  ('a raiz do problema',              'low_ticket', 'pt', 'low_ticket'),
  ('motivo real',                     'low_ticket', 'pt', 'low_ticket'),
  ('por que nada funciona',           'low_ticket', 'pt', 'low_ticket'),
  ('o que bloqueia seu corpo',        'low_ticket', 'pt', 'low_ticket'),
  ('razão escondida',                 'low_ticket', 'pt', 'low_ticket'),
  ('gatilho oculto',                  'low_ticket', 'pt', 'low_ticket'),
  ('trava hormonal',                  'low_ticket', 'pt', 'low_ticket'),
  ('comprovado',                      'low_ticket', 'pt', 'low_ticket'),
  ('estudos mostram',                 'low_ticket', 'pt', 'low_ticket'),
  ('estudo recente',                  'low_ticket', 'pt', 'low_ticket'),
  ('pesquisadores',                   'low_ticket', 'pt', 'low_ticket'),
  ('cientistas',                      'low_ticket', 'pt', 'low_ticket'),
  ('pesquisadores de harvard',        'low_ticket', 'pt', 'low_ticket'),
  ('especialistas',                   'low_ticket', 'pt', 'low_ticket'),
  ('médicos revelam',                 'low_ticket', 'pt', 'low_ticket'),
  ('testado e aprovado',              'low_ticket', 'pt', 'low_ticket'),
  ('baseado em pesquisas',            'low_ticket', 'pt', 'low_ticket'),
  ('chocante',                        'low_ticket', 'pt', 'low_ticket'),
  ('surpreendente',                   'low_ticket', 'pt', 'low_ticket'),
  ('bizarro',                         'low_ticket', 'pt', 'low_ticket'),
  ('estranho',                        'low_ticket', 'pt', 'low_ticket'),
  ('insólito',                        'low_ticket', 'pt', 'low_ticket'),
  ('escondido',                       'low_ticket', 'pt', 'low_ticket'),
  ('oculto',                          'low_ticket', 'pt', 'low_ticket'),
  ('esquecido',                       'low_ticket', 'pt', 'low_ticket'),
  ('mistério',                        'low_ticket', 'pt', 'low_ticket'),
  ('descoberta',                      'low_ticket', 'pt', 'low_ticket'),
  ('revelado',                        'low_ticket', 'pt', 'low_ticket'),
  ('finalmente revelado',             'low_ticket', 'pt', 'low_ticket'),
  ('descoberta acidental',            'low_ticket', 'pt', 'low_ticket'),
  -- EN
  ('trick',                           'low_ticket', 'en', 'low_ticket'),
  ('metod',                           'low_ticket', 'en', 'low_ticket'),
  ('watch the video',                 'low_ticket', 'en', 'low_ticket'),
  ('click below',                     'low_ticket', 'en', 'low_ticket'),
  ('learn more',                      'low_ticket', 'en', 'low_ticket'),
  ('free video',                      'low_ticket', 'en', 'low_ticket'),
  ('watch before removed',            'low_ticket', 'en', 'low_ticket'),
  ('protocol',                        'low_ticket', 'en', 'low_ticket'),
  ('secret',                          'low_ticket', 'en', 'low_ticket'),
  ('secret method',                   'low_ticket', 'en', 'low_ticket'),
  ('secret trick',                    'low_ticket', 'en', 'low_ticket'),
  ('simple trick',                    'low_ticket', 'en', 'low_ticket'),
  ('natural trick',                   'low_ticket', 'en', 'low_ticket'),
  ('hidden trick',                    'low_ticket', 'en', 'low_ticket'),
  ('homemade trick',                  'low_ticket', 'en', 'low_ticket'),
  ('weird trick',                     'low_ticket', 'en', 'low_ticket'),
  ('bizarre trick',                   'low_ticket', 'en', 'low_ticket'),
  ('strange trick',                   'low_ticket', 'en', 'low_ticket'),
  ('odd trick',                       'low_ticket', 'en', 'low_ticket'),
  ('10-second ritual',                'low_ticket', 'en', 'low_ticket'),
  ('15-second ritual',                'low_ticket', 'en', 'low_ticket'),
  ('hack',                            'low_ticket', 'en', 'low_ticket'),
  ('cheat',                           'low_ticket', 'en', 'low_ticket'),
  ('shortcut',                        'low_ticket', 'en', 'low_ticket'),
  ('discovery',                       'low_ticket', 'en', 'low_ticket'),
  ('ancient formula',                 'low_ticket', 'en', 'low_ticket'),
  ('forbidden method',                'low_ticket', 'en', 'low_ticket'),
  ('lost method',                     'low_ticket', 'en', 'low_ticket'),
  ('recipe',                          'low_ticket', 'en', 'low_ticket'),
  ('homemade',                        'low_ticket', 'en', 'low_ticket'),
  ('simple recipe',                   'low_ticket', 'en', 'low_ticket'),
  ('easy recipe',                     'low_ticket', 'en', 'low_ticket'),
  ('home remedy',                     'low_ticket', 'en', 'low_ticket'),
  ('home solution',                   'low_ticket', 'en', 'low_ticket'),
  ('natural remedy',                  'low_ticket', 'en', 'low_ticket'),
  ('natural method',                  'low_ticket', 'en', 'low_ticket'),
  ('natural solution',                'low_ticket', 'en', 'low_ticket'),
  ('herbal',                          'low_ticket', 'en', 'low_ticket'),
  ('herbal blend',                    'low_ticket', 'en', 'low_ticket'),
  ('ancient herb',                    'low_ticket', 'en', 'low_ticket'),
  ('root',                            'low_ticket', 'en', 'low_ticket'),
  ('spice',                           'low_ticket', 'en', 'low_ticket'),
  ('formula',                         'low_ticket', 'en', 'low_ticket'),
  ('drink',                           'low_ticket', 'en', 'low_ticket'),
  ('juice',                           'low_ticket', 'en', 'low_ticket'),
  ('mix',                             'low_ticket', 'en', 'low_ticket'),
  ('mixture',                         'low_ticket', 'en', 'low_ticket'),
  ('combination',                     'low_ticket', 'en', 'low_ticket'),
  ('banned',                          'low_ticket', 'en', 'low_ticket'),
  ('removed',                         'low_ticket', 'en', 'low_ticket'),
  ('taken down',                      'low_ticket', 'en', 'low_ticket'),
  ('deleted',                         'low_ticket', 'en', 'low_ticket'),
  ('before it''s removed',            'low_ticket', 'en', 'low_ticket'),
  ('they don''t want you to know',    'low_ticket', 'en', 'low_ticket'),
  ('hidden from the public',          'low_ticket', 'en', 'low_ticket'),
  ('secretly suppressed',             'low_ticket', 'en', 'low_ticket'),
  ('censored',                        'low_ticket', 'en', 'low_ticket'),
  ('forbidden',                       'low_ticket', 'en', 'low_ticket'),
  ('controversial',                   'low_ticket', 'en', 'low_ticket'),
  ('industry hates',                  'low_ticket', 'en', 'low_ticket'),
  ('big pharma hates',                'low_ticket', 'en', 'low_ticket'),
  ('blue pill industry hates',        'low_ticket', 'en', 'low_ticket'),
  ('shocking',                        'low_ticket', 'en', 'low_ticket'),
  ('strange',                         'low_ticket', 'en', 'low_ticket'),
  ('weird',                           'low_ticket', 'en', 'low_ticket'),
  ('unexpected',                      'low_ticket', 'en', 'low_ticket'),
  ('surprising',                      'low_ticket', 'en', 'low_ticket'),
  ('mind-blowing',                    'low_ticket', 'en', 'low_ticket'),
  ('eye-opening',                     'low_ticket', 'en', 'low_ticket'),
  ('hidden',                          'low_ticket', 'en', 'low_ticket'),
  ('unknown',                         'low_ticket', 'en', 'low_ticket'),
  ('little-known',                    'low_ticket', 'en', 'low_ticket'),
  ('untold',                          'low_ticket', 'en', 'low_ticket'),
  ('uncovered',                       'low_ticket', 'en', 'low_ticket'),
  ('revealed',                        'low_ticket', 'en', 'low_ticket'),
  ('pharmaceutical industry hates it','low_ticket', 'en', 'low_ticket'),
  ('kept hidden',                     'low_ticket', 'en', 'low_ticket'),
  ('industry doesn''t want you to know','low_ticket', 'en', 'low_ticket'),
  ('people are talking about it',     'low_ticket', 'en', 'low_ticket'),
  ('last chance',                     'low_ticket', 'en', 'low_ticket'),
  ('only available for a few hours',  'low_ticket', 'en', 'low_ticket'),
  ('watch before it goes offline',    'low_ticket', 'en', 'low_ticket'),
  ('video removed',                   'low_ticket', 'en', 'low_ticket'),
  ('limited time',                    'low_ticket', 'en', 'low_ticket'),
  ('don''t miss it',                  'low_ticket', 'en', 'low_ticket'),
  ('act now',                         'low_ticket', 'en', 'low_ticket'),
  ('click learn more',                'low_ticket', 'en', 'low_ticket'),
  ('confidence',                      'low_ticket', 'en', 'low_ticket'),
  ('people noticing',                 'low_ticket', 'en', 'low_ticket'),
  ('reversal ritual',                 'low_ticket', 'en', 'low_ticket'),
  ('homemade solution',               'low_ticket', 'en', 'low_ticket')
ON CONFLICT DO NOTHING;
